### ISSUE TITLE
Issue in 1.6.3 

### ISSUE THREAD

**Issue by Artistblock307** [vitormhenrique/xbox_chatpad_library#1]
Sorry about this. But i''m running into a problem where the example program along with other programs in where I tried to include it in don't work with the error;

Build options changed, rebuilding all

C:\Users\Samuel\Documents\Arduino\libraries\xbox_chatpad_library-master\Chatpad.cpp:26:20: fatal error: wiring.h: No such file or directory

 #include "wiring.h"

```
                ^
```

compilation terminated.

Error compiling.

Can you help?

**Comment by vitormhenrique** [comment]
Hi! there was an issue on the library on new Arduino versions. Fixed. Download and replace the old one, let me know if this fix the issue.

**Comment by vitormhenrique** [comment]
Closing this issue.
